#!/usr/bin/env bash
set -euo pipefail
DEC=".helix/decision.json"
TASKS="docs/TASKS.md"
PR="modules/genom/out/pr_draft.md"
mkdir -p modules/genom/out docs

action=$(jq -r '.decision.action' "$DEC")
ts=$(date -Iseconds)
echo "## $ts — ${action^^} plan" >> "$TASKS"
jq -r '.decision.goals[] | "- [ ] \(. )"' "$DEC" >> "$TASKS"
echo "" >> "$TASKS"

cat > "$PR" <<MD
# PR Draft — $ts
Action: $(jq -r '.decision.action' "$DEC")

## Goals
$(jq -r '.decision.goals[] | "- \(. )"' "$DEC")

## Proposed Changes
- Update POLICY thresholds if hardening
- Add/extend module tests
- Improve logging/observability

> Generated by Helix Guided Fixes
MD
echo "✅ guided fixes → $TASKS, $PR"
