name: trihelix-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.2.4)"
        required: true
  pull_request:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y python3

      - name: Ensure docs stubs (avoid missing-file failures)
        run: |
          mkdir -p docs
          test -f docs/RELEASE_NOTES.md || echo "No additional notes." > docs/RELEASE_NOTES.md
          test -f docs/CHANGELOG.md    || echo "- Initial." > docs/CHANGELOG.md

      - name: Generate notes & changelog
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ver="${{ inputs.version }}"
          else
            ver="v0.0.0"
          fi
          repo="${GITHUB_REPOSITORY}"
          base_tag="$(git describe --tags --abbrev=0 --tags --match 'v*' 2>/dev/null || echo v0.0.0)"
          compare_url="https://github.com/${repo}/compare/${base_tag}...${ver}"

          {
            echo "# TriHelix ${ver}"
            echo
            echo "## Summary"
            cat docs/RELEASE_NOTES.md
            echo
            echo "## Changelog"
            cat docs/CHANGELOG.md
            echo
            echo "## Links"
            echo "- Compare: ${compare_url}"
            echo "- Repo: https://github.com/${repo}"
          } > docs/RELEASE_BODY.md

      - name: Aggregate evaluation plans
        run: |
          python3 scripts/eval_aggregate.py
          if test -f docs/EVAL_SUMMARY.md; then
            {
              echo
              echo "## Evaluation Summary"
              cat docs/EVAL_SUMMARY.md
            } >> docs/RELEASE_BODY.md
          fi

      - name: Upload evaluation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eval-summary
          path: |
            docs/EVAL_SUMMARY.md
            docs/EVAL_SUMMARY.json

      - name: Create tag (dispatch only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          ver="${{ inputs.version }}"
          git tag -a "${ver}" -m "Release ${ver}"
          git push origin "${ver}"

      - name: Create GitHub Release (dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: TriHelix ${{ inputs.version }}
          body_path: docs/RELEASE_BODY.md
          draft: false
          prerelease: false
