name: trihelix-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.2.4)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Ensure docs stubs (never fail)
        run: |
          mkdir -p docs
          test -f docs/RELEASE_NOTES.md || echo "No manual notes for this release." > docs/RELEASE_NOTES.md
          test -f docs/CHANGELOG.md    || echo "# Changelog" > docs/CHANGELOG.md

      - name: Build release body
        shell: bash
        run: |
          set -euo pipefail
          ver="${{ github.event.inputs.version }}"
          repo="${GITHUB_REPOSITORY}"
          base_tag="$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || echo v0.0.0)"
          compare_url="https://github.com/${repo}/compare/${base_tag}...${ver}"
          {
            echo "# TriHelix ${ver}"
            echo
            echo "## Summary"
            cat docs/RELEASE_NOTES.md || true
            echo
            echo "## Changelog"
            cat docs/CHANGELOG.md || true
            echo
            echo "## Links"
            echo "- Compare: ${compare_url}"
            echo "- Repo: https://github.com/${repo}"
          } > docs/RELEASE_BODY.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: TriHelix ${{ github.event.inputs.version }}
          body_path: docs/RELEASE_BODY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
