name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. v1.2.3)"
        required: true
  pull_request:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y python3

      # Hər ikisində (PR və dispatch) təhlükəsiz generasiya: hec nə push/tag etmir
      - name: Generate notes & changelog (safe)
        run: |
          set -e
          chmod +x scripts/changelog.py scripts/release-notes.py || true

          # versiyanı kontekstdən götür: dispatch-də input, PR-da isə son tag + "-pr"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ver="${{ github.event.inputs.version }}"
          else
            last="$(git describe --tags --abbrev=0 --tags --match 'v*' 2>/dev/null || echo v0.0.0)"
            ver="${last}-pr"
          fi

          repo="${GITHUB_REPOSITORY}"
          compare_url="https://github.com/${repo}/compare/$(git describe --tags --abbrev=0 --tags --match 'v*' 2>/dev/null || echo v0.0.0)...${ver}"

          # changelog + notes
          python3 scripts/changelog.py
          python3 scripts/release-notes.py || true   # skript yoxdursa uğursuz etməsin

          # release body
          echo "# TriHelix ${ver}"            >  docs/RELEASE_BODY.md
          echo >> docs/RELEASE_BODY.md
          echo "## Summary"                   >> docs/RELEASE_BODY.md
          [ -f docs/RELEASE_NOTES.md ] && cat docs/RELEASE_NOTES.md >> docs/RELEASE_BODY.md || echo "(no notes)" >> docs/RELEASE_BODY.md
          echo >> docs/RELEASE_BODY.md
          echo "## Changelog"                 >> docs/RELEASE_BODY.md
          [ -f docs/CHANGELOG.md ] && cat docs/CHANGELOG.md >> docs/RELEASE_BODY.md || echo "(no changelog)" >> docs/RELEASE_BODY.md
          echo >> docs/RELEASE_BODY.md
          echo "## Links"                     >> docs/RELEASE_BODY.md
          echo "- Compare: ${compare_url}"    >> docs/RELEASE_BODY.md
          echo "- Repo: https://github.com/${repo}" >> docs/RELEASE_BODY.md

      # Aşağıdakı iki addım YALNIZ manual dispatch zamanı işləyir
      - name: Create tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          set -e
          ver="${{ github.event.inputs.version }}"
          git tag -a "$ver" -m "TriHelix $ver"
          git push origin "$ver"

      - name: Create GitHub Release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: TriHelix ${{ github.event.inputs.version }}
          body_path: docs/RELEASE_BODY.md
          overwrite_files: true
