name: trihelix-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  loop-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq python3
      - name: Run sync loop
        run: |
          chmod +x scripts/*.sh modules/*/bin/*.sh || true
          bash scripts/loop-run.sync.sh
      - name: Health Gate
        env:
          MIN_HEALTH: "75"
        run: |
          bash scripts/health-gate.sh
      - name: Prepare changes
        run: |
          git config user.name "helix-bot"
          git config user.email "helix-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "CHANGES=false" >> $GITHUB_ENV
          else
            git commit -m "chore(ci): loop telemetry & docs update"
            echo "CHANGES=true" >> $GITHUB_ENV
          fi
      - name: Create Pull Request
        if: env.CHANGES == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          commit-message: "chore(ci): loop telemetry & docs update"
          title: "Helix Bot: update telemetry & docs"
          body: |
            Automated update generated by Helix loop.
            Includes telemetry logs, metrics, insights, and roadmap deltas.
          branch: bot/helix-update
          delete-branch: true
          labels: bot, helix, automated
      - name: Optional webhook notify
        if: always()
        env:
          NOTIFY_WEBHOOK: ${{ secrets.NOTIFY_WEBHOOK }}
        run: |
          chmod +x scripts/notify-webhook.sh || true
          scripts/notify-webhook.sh "ci.complete" '{"status":"done"}' || true
